[tool.poetry]
name = "loading"
version = "0.1.0"
description = "Chapter V Exercise 1: Loading Programs"
authors = ["cvillene"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10.12"
pandas = "*"
numpy = "*"
matplotlib = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
